import 'primeicons/primeicons.css'
import '@/assets/css/tailwind.css'
import '@/assets/css/base.css'
import '@/assets/css/typography.css'
import '@/assets/css/main.css'
import '@/assets/css/custom.css'
import '@/assets/css/layout/index.scss'
